export default {
  GET_YEAR_REWARD_REQUEST: '@@year_reward/GET_YEAR_REWARD_REQUEST',
  GET_YEAR_REWARD_SUCCESS: '@@year_reward/GET_YEAR_REWARD_SUCCESS',
  ADD_YEAR_REWARD_REQUEST: '@@year_reward/ADD_YEAR_REWARD_REQUEST',
  ADD_YEAR_REWARD_SUCCESS: '@@year_reward/ADD_YEAR_REWARD_SUCCESS',
  UPDATE_YEAR_REWARD_REQUEST: '@@year_reward/UPDATE_YEAR_REWARD_REQUEST',
  UPDATE_YEAR_REWARD_SUCCESS: '@@year_reward/UPDATE_YEAR_REWARD_SUCCESS',
  DELETE_YEAR_REWARD_REQUEST: '@@year_reward/DELETE_YEAR_REWARD_REQUEST',
  DELETE_YEAR_REWARD_SUCCESS: '@@year_reward/DELETE_YEAR_REWARD_SUCCESS',
};