export default {
  GET_RECIPES_REQUEST: '@@recipes/GET_RECIPES_REQUEST',
  GET_RECIPES_SUCCESS: '@@recipes/GET_RECIPES_SUCCESS',
  ADD_RECIPES_REQUEST: '@@recipes/ADD_RECIPES_REQUEST',
  ADD_RECIPES_SUCCESS: '@@recipes/ADD_RECIPES_SUCCESS',
  UPDATE_RECIPES_REQUEST: '@@recipes/UPDATE_RECIPES_REQUEST',
  UPDATE_RECIPES_SUCCESS: '@@recipes/UPDATE_RECIPES_SUCCESS',
  DELETE_RECIPES_REQUEST: '@@recipes/DELETE_RECIPES_REQUEST',
  DELETE_RECIPES_SUCCESS: '@@recipes/DELETE_RECIPES_SUCCESS',
};