export default {
  GET_INGREDIENTS_REQUEST: '@@ingredients/GET_INGREDIENTS_REQUEST',
  GET_INGREDIENTS_SUCCESS: '@@ingredients/GET_INGREDIENTS_SUCCESS',
  ADD_INGREDIENTS_REQUEST: '@@ingredients/ADD_INGREDIENTS_REQUEST',
  ADD_INGREDIENTS_SUCCESS: '@@ingredients/ADD_INGREDIENTS_SUCCESS',
  UPDATE_INGREDIENTS_REQUEST: '@@ingredients/UPDATE_INGREDIENTS_REQUEST',
  UPDATE_INGREDIENTS_SUCCESS: '@@ingredients/UPDATE_INGREDIENTS_SUCCESS',
  DELETE_INGREDIENTS_REQUEST: '@@ingredients/DELETE_INGREDIENTS_REQUEST',
  DELETE_INGREDIENTS_SUCCESS: '@@ingredients/DELETE_INGREDIENTS_SUCCESS',
};